name: Run tests

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Check formatting and run tests
        run: |
          npm run build
          npm run autoformat:check
          npm run test
