name: Run mutation testing experiment

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages to generate tests for"
        default: "+benchmarks.txt"
      temperatures:
        description: "Sampling temperatures to try when obtaining completions (whitespace-separated)"
        default: "0.0"
      numCompletions:
        description: "Number of completions to generate for each prompt"
        default: "5"
      model:
        description: "Which LLM API to use"
        type: "choice"
        options:
          - "gpt"
          - "starcoder"
          - "davinci"
        default: "davinci"
      skipSlowBenchmarks:
        description: "Skip slow benchmarks"
        type: boolean
        default: false
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        default: false
  # Run every weekday at 2:00 AM UTC
  # schedule:
  #   - cron: '0 2 * * 1-5'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      packages: "${{ steps.parse_packages.outputs.packages }}"
      temperatures: "${{ github.event.inputs.temperatures || '0.0' }}"
      numCompletions: "${{ github.event.inputs.numCompletions || '5' }}"
      model: "${{ github.event.inputs.model || 'davinci' }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - id: parse_packages
        run: |
          packages=$(node ${GITHUB_WORKSPACE}/.github/parse_packages.js \
            ${{ github.event.inputs.skipSlowBenchmarks == 'true' && '--skip-slow-benchmarks' || '' }} \
            "${{ github.event.inputs.packages || '+benchmarks.txt' }}")
          echo "packages=$packages" >> $GITHUB_OUTPUT

  benchmark:
    needs:
      - setup
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.setup.outputs.packages) }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: llm-mutation-testing

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Set up llm-mutation-testing
        run: |
          cd llm-mutation-testing
          npm run build