name: Stryker experiment

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: checkout master branch of StrykerJS from https://github.com/franktip/stryker-js into directory stryker-js
        uses: actions/checkout@v3
        with:
          repository: franktip/stryker-js
          ref: master
          path: stryker-js

      - name: build StrykerJS
        run: |
          cd stryker-js
          npm install
          npm run build
      
      - name: Check out https://github.com/maugenst/zip-a-folder/tree/d2ea465b20dc33cf8c98c58a7acaf875c586c3e1 into directory PROJECT
        uses: actions/checkout@v3
        with:
          repository: manuelmhtr/countries-and-timezones
          ref: 241dd0f56dfc527bcd87779ae14ed67bd25c1c0e
          path: PROJECT

      - name: go into project and install install-local
        run: |
          cd PROJECT
          npm install install-local
          

      - name: go into PROJECT and install stryker-js locally
        run: |
          cd PROJECT
          npx install-local ../stryker-js/packages/{core,util,api,instrumenter,*-runner}  --legacy-peer-deps

      - name: build project
        run: |
          cd PROJECT
          npm install
          npm run build

      - name: run stryker
        run: |
          cd PROJECT
          echo "pwd"
          pwd
          echo "ls"
          ls
          npx stryker run --mutate **/src/build-country.js,**/src/build-timezone.js,**/src/index.js

      # - name: Check formatting and run tests
      #   run: |
      #     npm run build
      #     npm run autoformat:check
      #     npm run test
