name: Stryker experiment

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  run-stryker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: checkout master branch of StrykerJS from https://github.com/franktip/stryker-js into directory stryker-js
        uses: actions/checkout@v3
        with:
          repository: franktip/stryker-js
          ref: master
          path: stryker-js

      - name: build StrykerJS
        run: |
          cd stryker-js
          npm install
          npm run build
      
      - name: Check out https://github.com/maugenst/zip-a-folder/tree/d2ea465b20dc33cf8c98c58a7acaf875c586c3e1 into directory PROJECT
        uses: actions/checkout@v3
        with:
          repository: maugenst/zip-a-folder
          ref: d2ea465b20dc33cf8c98c58a7acaf875c586c3e1
          path: PROJECT

      - name: go into project and install install-local
        run: |
          cd PROJECT
          npm install install-local
      - name: go into PROJECT and install stryker-js locally
        run: |
          cd PROJECT
          npx install-local ../stryker-js/packages/{core,util,api,instrumenter,*-runner}  --legacy-peer-deps
          echo "check stryker version"
          npx stryker --version  # prints 8.2.5
      - name: build project
        run: |
          cd PROJECT
          npm run build
          echo "check stryker version (2)"
          npx stryker --version
      - name: run stryker (standard mutators)
        run: |
          cd PROJECT
          npx stryker run --mutate **/ZipAFolder.ts
      - name: run stryker (precomputed mutators)
        run: |
          cd PROJECT
          export MUTANTS_FILE=MUTATION_TESTING/template1_codellama-34b-instruct_0/mutants.json
          npx stryker run --usePrecomputed --mutate **/ZipAFolder.ts
